version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: moneta_backend
    ports:
      - "8008:8008"
    volumes:
      - moneta_data:/app
      - ./backend/uploads:/app/uploads
    restart: always
    # Environment variables (hardcoded for now as requested)
    environment:
      - PORT=8008
      - HOST=0.0.0.0

  frontend:
    build:
      context: ./frontend
    container_name: moneta_frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

volumes:
  moneta_data:
